# From "Thinking in C++, 2nd Edition, Volume 1, 
# Annotated Solutions Guide" by Chuck Allison
# At http://www.BruceEckel.com
# (c)2001 MindView Inc. Copyright notice in Copyright.txt
# Automatically-generated MAKEFILE 
# For examples in directory .\S02
# Invoke with: make

CPP = bcc32
OFLAGS = -c
EXEFLAG = -e
OBJEXT = obj
.SUFFIXES : .cpp .$(OBJEXT) .exe
.cpp.$(OBJEXT) :
	$(CPP) $(OFLAGS) $<
.cpp.exe :
	$(CPP) $< $(EXEFLAG)$@

borland:  \
	Hello2.exe \
	Area.exe \
	Words.exe \
	Words2.exe \
	WordCount.exe \
	Fillvector.exe \
	Fillvector2.exe \
	FileView.exe \
	FloatVector.exe \
	FloatVector2.exe \
	FloatVector3.exe

microsoft:  \
	Hello2.exe \
	Area.exe \
	Words.exe \
	Words2.exe \
	WordCount.exe \
	Fillvector.exe \
	Fillvector2.exe \
	FileView.exe \
	FloatVector.exe \
	FloatVector2.exe \
	FloatVector3.exe

g++295:  \
	Hello2.exe \
	Area.exe \
	Words.exe \
	Words2.exe \
	WordCount.exe \
	Fillvector.exe \
	Fillvector2.exe \
	FileView.exe \
	FloatVector.exe \
	FloatVector2.exe \
	FloatVector3.exe

g++3:  \
	Hello2.exe \
	Area.exe \
	Words.exe \
	Words2.exe \
	WordCount.exe \
	Fillvector.exe \
	Fillvector2.exe \
	FileView.exe \
	FloatVector.exe \
	FloatVector2.exe \
	FloatVector3.exe

edg:  \
	Hello2.exe \
	Area.exe \
	Words.exe \
	Words2.exe \
	WordCount.exe \
	Fillvector.exe \
	Fillvector2.exe \
	FileView.exe \
	FloatVector.exe \
	FloatVector2.exe \
	FloatVector3.exe


Hello2.exe: Hello2.cpp

Area.exe: Area.cpp

Words.exe: Words.cpp

Words2.exe: Words2.cpp

WordCount.exe: WordCount.cpp

Fillvector.exe: Fillvector.cpp

Fillvector2.exe: Fillvector2.cpp

FileView.exe: FileView.cpp

FloatVector.exe: FloatVector.cpp

FloatVector2.exe: FloatVector2.cpp

FloatVector3.exe: FloatVector3.cpp

